Traceback (most recent call last):
  File "/app/create_download_server.py", line 122, in <module>
    start_download_server()
  File "/app/create_download_server.py", line 95, in start_download_server
    server = HTTPServer(('0.0.0.0', 8080), DownloadHandler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.11/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
